[[servers]]
name = "deathrun"
exclude = ["double-jump", "awarn3"]

[[servers]]
name = "murder"

[[servers]]
name = "terrortown"
exclude = ["voicechat-meter", "voicechat-charger", "crosshair-creator"]
