[package]
name = "lory"
version = "0.1.0"
authors = ["ceifa <gabrinelson27@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.5.6"
serde = "1.0.110"
serde_derive = "1.0.110"
fs_extra = "1.1.0"
symlink = "0.1.0"